### Get all orders
GET http://localhost:9090/product_manager_paklenica/order/
Accept: application/json

### Get all orders
GET http://localhost:9090/product_manager_paklenica/order/63250a69-9621-49f0-9641-d006ed49e71d
Accept: application/json

### Get active orders
GET http://localhost:9090/product_manager_paklenica/order/active
Accept: application/json

### Save order
POST http://localhost:9090/product_manager_paklenica/order/
Content-Type: application/json

{
  "active": true,
  "createdDateTime": "2024-09-06T12:00:00",
  "expectedDeliveryDate": "2024-09-06",
  "store": {
    "name": "9-eleven",
    "address": {
      "city": "New York",
      "country": "USA",
      "street": "5th Avenue",
      "number": "101"
    },
    "phoneNumber": "01-234-567-8900",
    "email": "info@nineeleven.com",
    "workingDays": [
      {
        "day": "MONDAY",
        "startTime": "09:00:00",
        "endTime": "17:00:00"
      },
      {
        "day": "TUESDAY",
        "startTime": "09:00:00",
        "endTime": "17:00:00"
      }
    ]
  },
  "employee": {
    "firstName": "Filip",
    "lastName": "Gale",
    "dateOfBirth": "2024-09-06",
    "idNumber": "12345678901",
    "hireDate": "2024-09-06",
    "experienceYears": 5.0,
    "vacationDays": 0,
    "position": {
      "title": "DRIVER",
      "level": "SENIOR"
    }
  },
  "productsMetadata": {
    "created": "2024-09-06T12:00:00",
    "description": "lista",
    "products": [
      {
        "name": "keks",
        "price": 1,
        "currency": "Eur",
        "stockQuantity": 5
      },
      {
        "name": "keks",
        "price": 1,
        "currency": "Eur",
        "stockQuantity": 5
      }
    ]
  }
}

### Deactivate order
PUT http://localhost:9090/product_manager_paklenica/order/orderUpdate/63250a69-9621-49f0-9641-d006ed49e71d
Accept: application/json
